FROM node:22-bookworm-slim

ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=5645

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 5645

CMD ["npx", "next", "dev", "--webpack", "-H", "0.0.0.0", "-p", "5645"]
